@CorpTablesInquireOnTables @Fusion
Feature: Corp Tables
  I want to be able to navigate to the Corp Tables page and view list of descriptions of  tables

  Background: Manual Execution Effort For Automation Metrics
    Given Manual Execution Effort is 00:18:00


  @CorpTables
  Scenario Outline: Navigate to Corp Table page, select a table,verify that all expected columns are displayed, search on a full/partial Provider ID and verify the record(s) with the provider ID are displayed
    Given User is on the Fusion Home screen
    Then User switch to "Test Analyst" role
    And User Select Corp Tables Link
    Then User verify table name <TableName> displays on one of the pages and select it
    And User verify results table displays for Corp Table <TableName>
    Then User verify table header values as <Pega Table Header>
    When User search on a partial or full ProviderOrTax ID <Search Value>
    Then User verify records with search value <Search Value> displays in search column <SearchColumn> on webpage
   # Then User verify records with tax id <Search Value> displays for Tax Id search
    Then User verify Pega table values with DB table <DBTableName> on Columns <DB Columns>
    Then User compare the excel data <Excel Path> vs DB table <DBTableName> on Columns <DB Columns>
    And User log off and close the browser

    Examples:
      | TableName                                                           | Excel Path                              | DBTableName                      | Search Value | SearchColumn                                                                              | Pega Table Header                                                                            | DB Columns                                                                                     |
      | "Set Direction of Payment, Network Status, Pay Sub - 0111"          | "C:/StoryData/PRDFEPFUS-9471-Data.xlsx" | "FHPSCD_DIROFPYMT_111"           | "320121856"  | "Provider ID"                                                                             | "State,  Provider ID, Tax ID, Direction Of Payment, Network Status, Pay Sub Indicator"       | "PYSTATE,PROVIDERID,TAXIDENTIFICATIONNUMBER,DIRECTIONOFPAYMENT,NETWORKSTATUS,PAYSUBINDICATOR"  |
      | "NY Physician Office Lab (POL) Provider Exclusions - 164"           | "C:/StoryData/PRDFEPFUS-7885-Data.xlsx" | "FHPSCD_NYPOL_PROV_EXCLN_164"    | "272873874"  | "Tax ID, Description"                                                                     | "code, description"                                                                          |                                                                                                |
      | "Set Override Code Based on Provider Par Status Table - 302"        | "C:/StoryData/PRDFEPFUS-7861-Data.xlsx" | "FHPSCD_OVERRIDE_PAR_NONPAR_302" | "002"        | "Override, Preferred and Participating, Non Participating, Add Override, Description"     | "OVERRIDE,PAR,NONPAR,ADDOVERRIDE,DESCRIPTION"                                                |                                                                                                |
      | "Provider Network Special Processing - 319"                         | "C:/StoryData/PRDFEPFUS-8061-Data.xlsx" | "FHPSCD_PROV_NWK_SPLPROCESS_319" | "5230"       | "State, Tax ID, Provider ID, Description"                                                 | "PYSTATE,TAXIDENTIFICATIONNUMBER,PROVIDERID,DESCRIPTION"                                     |                                                                                                |
      | "NY Physician Office Lab (POL) Procedure Code Exclusions - 165"     | "C:/StoryData/PRDFEPFUS-9384-Data.xlsx" | "FHPSCD_NYPOL_PROC_EXCLN_165"    | "U0004"      | "Procedure code,Description"                                                              | "CODE, DESCRIPTION"                                                                          |                                                                                                |
      | "NY Physician Office Lab (POL) Provider Exclusions - 164"           | "C:/StoryData/PRDFEPFUS-9385-Data.xlsx" | "FHPSCD_NYPOL_PROV_EXCLN_164"    | "100329379"  | "Tax ID"                                                                                  | "Tax ID,Description"                                                                         | "CODE,DESCRIPTION"                                                                             |
      | "NY HCPCS Eligible for Bundling NYCHRA"                             | "C:/StoryData/PRDFEPFUS-7879-Data.xlsx" | "FHPSCD_NYHCRABundling_162"      | "G0027"      | "Procedure code,Description"                                                              | "CODE,DESCRIPTION"                                                                           |                                                                                                |
      | "NPI CrossWalk: Rendering vs Billing - 105"                         | "C:/StoryData/PRDFEPFUS-7932-Data.xlsx" | "FHPSCD_NPI_XWLK_BILL_REND_105"  | "869073"     | "State,NPI,Use Rendering NPI, Use Billing NPI, Use Rendering Address,Use Billing Address" | "PYSTATE,NPI,USERENDERINGNPI,USEBILLINGNPI,USERENDERINGADDRESS,USEBILLINGADDRESS"            |                                                                                                |
      | "NDC Deny Codes"                                                    | "C:/StoryData/PRDFEPFUS-8408-Data.xlsx" | "FHPSCD_NDC_DENYCODES_130"       | "XENICAL"    | "NDC Numbers,Drug name, Denial reason"                                                    | "CODE,DESCRIPTION,DENIALCODE"                                                                |                                                                                                |
      | "Professional Claim Lines Not Sent to CXT - 720"                    | "C:/StoryData/PRDFEPFUS-7893-Data.xlsx" | "FHPSCD_CXT_EXCEPTIONS_720"      | "MED"        | "Fields, Values"                                                                          | "CODE, DESCRIPTION"                                                                          |                                                                                                |
      | "Onduo HCPCs and Providers - 867"                                   | "C:/StoryData/PRDFEPFUS-8587-Data.xlsx" | "fhpscd_onduo_hcpcs_codes_867"   | "NY"         | "State"                                                                                   | "State, HCPCS, NPI, Tax ID,Description"                                                      | "PYSTATE, HCPC, NPI, TAXIDENTIFICATIONNUMBER, DESCRIPTION"                                     |
      | "CO/NV Non Participating Professional Product Codes - 0109"         | "C:/StoryData/PRDFEPFUS-8768-Data.xlsx" | "FHPSCD_CO_NV_PROF_NONPAR_109"   | "ZBHB"       | "Product Code"                                                                            | "Product  Code,Description"                                                                  | "Code, DESCRIPTION"                                                                            |
      | "Procedure Codes in POS 21 to Set Override AFTN - 0792"             | "C:/StoryData/PRDFEPFUS-7941-Data.xlsx" | "FHPSCD_POS21_OVERRIDE_792 "     | "C8900"      | "Procedure code"                                                                          | "Procedure code,Override"                                                                    | "Code, DESCRIPTION"                                                                            |
      | "NY HCPCS Eligible for Bundling NYCHRA"                             | "C:/StoryData/PRDFEPFUS-9383-Data.xlsx" | "FHPSCD_NYHCRABUNDLING_162 "     | "G0123"      | "Code"                                                                                    | "Procedure code,Description"                                                                 | "Code, DESCRIPTION"                                                                            |
      | "Out of Area Providers - 0463"                                      | "C:/StoryData/PRDFEPFUS-9470-Data.xlsx" | "FHPSCD_OOA_PROV_463"            | "NY"         | "State"                                                                                   | "State, Tax ID, Zip Code, Zip Code Extension, Provider ID, Applies to Medicare Claims (Y/N)" | "PYSTATE, TAXIDENTIFICATIONNUMBER, ZIPCODE, ZIPCODEEXTN, PROVIDERID, MEDPARIND"                |
      | "Timely Filing Exceptions"                                          | "C:/StoryData/PRDFEPFUS-9351-Data.xlsx" | "FHPSCD_TIMELYFILINGEXCPN_999"   | "NY"         | "State"                                                                                   | "Claim Type,State, Provider ID, Tax ID, Effective date, End date, Timely Filing Days"        | "CLAIMTYPE, PYSTATE, PROVIDERID, TAXIDENTIFICATIONNUMBER, EFFECTIVEDATE, EXPIRATIONDATE, DAYS" |
      | "Timely Filing Days"                                                | "C:/StoryData/PRDFEPFUS-9377-Data.xlsx" | "FHPSCD_TIMELYFILINGDAYS_998"    | "NY"         | "State"                                                                                   | "State, Days, Claim Type"                                                                    | "PYSTATE, DAYS, CLAIMTYPE"                                                                     |
      | "Facility Claim Lines Not Sent Through Diagnosis Policy - 0724"     | "C:/StoryData/PRDFEPFUS-9043-Data.xlsx" | "FHPSCD_FAC_DX_EXCPN_724"        | "MED"        | "Fields"                                                                                  | "Fields, Values"                                                                             | "Code, DESCRIPTION"                                                                            |
      | "Novologix Exceptions - 315"                                        | "C:/StoryData/PRDFEPFUS-8201-Data.xlsx" | "FHPSCD_FAC_DX_EXCPN_724"        | "IN"         | "State"                                                                                   | "State, Provider ID, Description"                                                            | "PYSTATE, PROVIDERID,DESCRIPTION"                                                              |
      | "Medicaid Provider Numbers - 311"                                   | "C:/StoryData/PRDFEPFUS-7492-Data.xlsx" | "FHPSCD_MEDICAID_PROVIDERS_311"  | "CA"         | "State"                                                                                   | "State, Provider ID, Description"                                                            | "PYSTATE, PROVIDERID, DESCRIPTION"                                                             |
      | "Timely Filing: CPT/Revenue/Diagnosis/Description Exceptions - 380" | "C:/StoryData/PRDFEPFUS-9378-Data.xlsx" | "FHPSCD_TIMELYFILING_EXPNCD_380" | "86408"      | "CPT"                                                                                     | "CPT, Revenue code, Diagnosis code, Term date, Description"                                  | "CPTCODE, REVENUECODE,DIAGNOSISCODE,EXPIRATIONDATE, DESCRIPTION"                               |
      | "Provider Specialty Code Conversion - 0760"                         | "C:/StoryData/PRDFEPFUS-9808-Data.xlsx" | "FHPSCD_PROV_SPECIALTY_CONV_760" | "100"        | "WGS Specialty Code"                                                                      | "WGS Specialty Code (SPS) ,FEP Specialty Code"                                               | "WGSSPECIALTY, FEPSPECIALTY, DESCRIPTION"                                                      |

  
  